### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mhooton** [bmorris3/kelp#20]
Getting the following when upgrading via pip

```
Collecting git+https://github.com/bmorris3/kelp.git
  Cloning https://github.com/bmorris3/kelp.git to /private/tmp/pip-req-build-ee5peunp
  Running command git clone -q https://github.com/bmorris3/kelp.git /private/tmp/pip-req-build-ee5peunp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: astropy in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from kelp==0.5.dev7+g8310af6) (4.0.1.post1)
Requirement already satisfied: matplotlib in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from kelp==0.5.dev7+g8310af6) (3.2.2)
Requirement already satisfied: scipy in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from kelp==0.5.dev7+g8310af6) (1.5.2)
Requirement already satisfied: numpy>=1.16 in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from astropy->kelp==0.5.dev7+g8310af6) (1.19.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from matplotlib->kelp==0.5.dev7+g8310af6) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from matplotlib->kelp==0.5.dev7+g8310af6) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from matplotlib->kelp==0.5.dev7+g8310af6) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from matplotlib->kelp==0.5.dev7+g8310af6) (1.3.1)
Requirement already satisfied: six in /Users/mhooton/anaconda3/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->kelp==0.5.dev7+g8310af6) (1.15.0)
Building wheels for collected packages: kelp
  Building wheel for kelp (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mhooton/anaconda3/bin/python /Users/mhooton/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmphy6e233c
       cwd: /private/tmp/pip-req-build-ee5peunp
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/conftest.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/version.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/_astropy_init.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/core.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  copying kelp/registries.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
  creating build/lib.macosx-10.9-x86_64-3.7/kelp/tests
  copying kelp/tests/test_theano.py -> build/lib.macosx-10.9-x86_64-3.7/kelp/tests
  copying kelp/tests/test_core.py -> build/lib.macosx-10.9-x86_64-3.7/kelp/tests
  copying kelp/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/kelp/tests
  creating build/lib.macosx-10.9-x86_64-3.7/kelp/theano
  copying kelp/theano/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/kelp/theano
  copying kelp/theano/theano.py -> build/lib.macosx-10.9-x86_64-3.7/kelp/theano
  creating build/lib.macosx-10.9-x86_64-3.7/kelp/data
  copying kelp/data/planets.json -> build/lib.macosx-10.9-x86_64-3.7/kelp/data
  copying kelp/data/filters.json -> build/lib.macosx-10.9-x86_64-3.7/kelp/data
  copying kelp/data/README.rst -> build/lib.macosx-10.9-x86_64-3.7/kelp/data
  running build_ext
  building 'kelp.fast' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/kelp
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mhooton/anaconda3/include -arch x86_64 -I/Users/mhooton/anaconda3/include -arch x86_64 -I/private/tmp/pip-build-env-0ky9az9h/overlay/lib/python3.7/site-packages/numpy/core/include -I/Users/mhooton/anaconda3/include/python3.7m -c kelp/fast.c -o build/temp.macosx-10.9-x86_64-3.7/kelp/fast.o
  In file included from /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/syslimits.h:7,
                   from /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/limits.h:34,
                   from /Users/mhooton/anaconda3/include/python3.7m/Python.h:11,
                   from kelp/fast.c:26:
  /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/limits.h:195:61: error: no include path in which to search for limits.h
    195 | #include_next <limits.h>  /* recurse down to the real one */
        |                                                             ^
  In file included from /Users/mhooton/anaconda3/include/python3.7m/Python.h:25,
                   from kelp/fast.c:26:
  /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
     78 | #include <_stdio.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for kelp
Failed to build kelp
ERROR: Could not build wheels for kelp which use PEP 517 and cannot be installed directly
```

**Comment by mhooton** [comment]
And the following when pulling from github:

running install
running bdist_egg
running egg_info
writing kelp.egg-info/PKG-INFO
writing dependency_links to kelp.egg-info/dependency_links.txt
writing requirements to kelp.egg-info/requires.txt
writing top-level names to kelp.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching 'LICENSE.rst'
warning: no files found matching '*.pxd' under directory 'kelp'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.fits' found anywhere in distribution
writing manifest file 'kelp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
copying kelp/version.py -> build/lib.macosx-10.9-x86_64-3.7/kelp
running build_ext
building 'kelp.fast' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mhooton/anaconda3/include -arch x86_64 -I/Users/mhooton/anaconda3/include -arch x86_64 -I/Users/mhooton/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/mhooton/anaconda3/include/python3.7m -c kelp/fast.c -o build/temp.macosx-10.9-x86_64-3.7/kelp/fast.o
In file included from /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/syslimits.h:7,
                 from /opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/limits.h:34,
                 from /Users/mhooton/anaconda3/include/python3.7m/Python.h:11,
                 from kelp/fast.c:23:
/opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/limits.h:195:61: error: no include path in which to search for limits.h
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |                                                             ^
In file included from /Users/mhooton/anaconda3/include/python3.7m/Python.h:25,
                 from kelp/fast.c:23:
/opt/local/lib/gcc10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
   78 | #include <_stdio.h>
      |          ^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by bmorris3** [comment]
Hi @mhooton! Let's sort this out. 

It looks like [this is the most likely solution](https://github.com/Microsoft/LightGBM/issues/1420#issuecomment-394664383).

Some questions: 
* what version of OS X are you running? 
* did kelp work on this machine before?
* do you have XCode Command Line Tools installed on this machine, and if so, could you check which version?

**Comment by bmorris3** [comment]
I just found that I get a similar issue with the latest kelp on OS X 10.14, which I solved by following [these instructions](https://stackoverflow.com/a/52511046).
