### ISSUE TITLE
Wrong reflected light curve for alpha == 0

### ISSUE THREAD

**Issue by delinea** [bmorris3/kelp#27]
In *kelp/core.py*, the reflected light curve is computed for any values of *alpha*.
The values of Psi_0, Psi_S and Psi_C are not finite for alpha == 0 or alpha == pi.
This is corrected at lines 165-166 by:
```
# Fix the case when the phase angle is exactly 0 or 1:
Psi[np.isnan(Psi)] = 0
```
However, **this correction is wrong for alpha == 0, where Psi should be maximal.**

A suggestion would be to insert the following lines in the code before computing the values of Psi (at line 156, for instance) :
```
# Fix the case when the phase angle is exactly 0 or 
Psi_S[abs_alpha == 0] = 1
Psi_C[abs_alpha == 0] = 2/3.
Psi_S[abs_alpha == np.pi] = 0
Psi_C[abs_alpha == np.pi] = 0
```

In this case, the correction `Psi[np.isnan(Psi)] = 0` is no more required.

**Comment by bmorris3** [comment]
Hi @delinea, 

Thanks for this, I've been investigating this corner case as well. It seems like [this tweak fixes it in the jax implementation](https://github.com/bmorris3/kelp/blob/master/kelp/jax/jax.py#L615-L621). I'll investigate how this does for cython.
