### ISSUE TITLE
ImportError astropy.config.configuration.update_default_config

### ISSUE THREAD

**Issue by odemangeon** [bmorris3/kelp#40]
Hi,

I have recently installed the new version of kelp using pip and I got the following error at import:

"ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration'"

It appears that update_default_config has been removed from the last version of astropy (6.0.0). As I am not familiar with what this function was doing and how this was used in kelp. I am not sure how the code needs to be changed to take that into account. So I have downgraded my astropy to 5.3.4. You might want to change the requirements or modify the code to adapt to this depreciation.

Best wishes.

**Comment by bmorris3** [comment]
Hi @odemangeon, thanks for the note! Do you still have the full traceback? I'll fix this ASAP.

**Comment by odemangeon** [comment]
You were faster fixing it than me giving you the info you asked. :)

I have to run now, but I will try your fix tomorrow.

Just in case this is the full error trace back.
>>> import kelp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "***/anaconda3/envs/tmp/lib/python3.9/site-packages/kelp/__init__.py", line 6, in <module>
    from ._astropy_init import *   # noqa
  File "***/anaconda3/envs/tmp/lib/python3.9/site-packages/kelp/_astropy_init.py", line 21, in <module>
    from astropy.config.configuration import (
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' (***/anaconda3/envs/tmp/lib/python3.9/site-packages/astropy/config/configuration.py)

I assume that
