### ISSUE TITLE
Model import error

### ISSUE THREAD

**Issue by mhooton** [bmorris3/kelp#7]
Just installed the latest version, am now getting the following error

```
---> 44 from kelp import Model

~/anaconda3/lib/python3.7/site-packages/kelp/__init__.py in <module>
      7 # ----------------------------------------------------------------------------
      8 
----> 9 from .core import *  # noqa
     10 from .registries import *  # noqa
     11 from .fast import *  # noqa

~/anaconda3/lib/python3.7/site-packages/kelp/core.py in <module>
      6 
      7 from .registries import PhaseCurve
----> 8 from .fast import h_ml_sum_cy, integrated_blackbody, phase_curve
      9 
     10 from astropy.modeling.models import BlackBody

__init__.pxd in init kelp.fast()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by bmorris3** [comment]
Hi @mhooton! 

Thanks for this. That's a bit odd because the [tests seem to have passed](https://github.com/bmorris3/kelp/runs/1821675399). It looks like it may be a binary link to an old file that's causing this error. Would you please try: 
```
pip uninstall kelp   # Repeat this until it says "not found"
python setup.py install   # in the repo source dir
tox -e test   # runs the tests
```

**Comment by KathrynJones1** [comment]
hmm no I actually get this error when I run that: 
`Warning, treated as error:
dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
ERROR: InvocationError for command /Users/jones/Dropbox/Packages/kelp/.tox/build_docs/bin/sphinx-build -W -b html . _build/html (exited with code 2)`
